Repository HUSTLE-UMC/HUSTLE_web, pull requests merged in 2023-08, with the labels that each got.

#41 Style/#38 교류전 로직 오류 해결 및 일부 스타일 수정
  hustle_web/src/components/Community/Question/QuestionForm.tsx
  hustle_web/src/components/FriendlyMatchPage/ApplyMatch/MatchInvitation.tsx
  hustle_web/src/components/FriendlyMatchPage/ApplyMatch/MatchRequest.tsx
  hustle_web/src/components/FriendlyMatchPage/FriendlyMatchList/FriendlyMatchList.tsx
  hustle_web/src/components/FriendlyMatchPage/FriendlyMatchList/MatchListProps.ts
  hustle_web/src/components/FriendlyMatchPage/MainMatch/MainMatch.tsx
  hustle_web/src/components/FriendlyMatchPage/MainMatch/MatchLists/InvitationLists.tsx
  hustle_web/src/components/FriendlyMatchPage/MainMatch/MatchLists/MatchLists.tsx
  hustle_web/src/components/FriendlyMatchPage/MainMatch/MatchTitle/Styles.tsx
  hustle_web/src/components/FriendlyMatchPage/MainMatch/Styles.tsx
  hustle_web/src/components/FriendlyMatchPage/PostMatch/PostFormLeft.tsx
  hustle_web/src/components/FriendlyMatchPage/PostMatch/PostFormRight.tsx
  hustle_web/src/components/FriendlyMatchPage/PostMatch/PostMatch.tsx
  hustle_web/src/components/FriendlyMatchPage/SubmitButton/ButtonProps.ts
  hustle_web/src/components/FriendlyMatchPage/SubmitButton/Styles.tsx
  hustle_web/src/components/FriendlyMatchPage/SubmitButton/SubmitButton.tsx
  hustle_web/src/components/SportsButton/SportsButton.tsx
  hustle_web/src/components/SportsButton/Styles.tsx
  hustle_web/src/components/SportsMenu/SportsMenu.tsx
  hustle_web/src/components/SportsMenu/Styles.tsx
  hustle_web/src/recoil/SportsButton.tsx
  hustle_web/src/recoil/friendlyMatchPage/states.tsx
  hustle_web/src/stories/assets/Writing.svg
  hustle_web/src/styles/Font.ts
Labels: Fix, Style

#44 Feat/#40 헤더 화면 구성
  hustle_web/src/assets/icons/profile_icon.svg
  hustle_web/src/components/Auth/AuthProvider.tsx
  hustle_web/src/components/Auth/LoginComponent.tsx
  hustle_web/src/components/Auth/NotLoginComponent.tsx
  hustle_web/src/components/Header/Styles.tsx
  hustle_web/src/components/Header/index.tsx
  hustle_web/src/components/Login/Login.tsx
  hustle_web/src/constants/defaultFormOption.ts
  hustle_web/src/recoil/login/loginState.tsx
Labels: Feature, 베니/김도희

#51 Refactor: 회원가입 화면 리펙토링
  hustle_web/src/Router.tsx
  hustle_web/src/components/SignIn/SignIn.tsx
  hustle_web/src/components/SignIn/Styles.ts
  hustle_web/src/pages/SignIn/Styles.tsx
  hustle_web/src/pages/SignIn/index.tsx
  hustle_web/src/routes.ts
Labels: Refactor, 데이브/김원준

#62 Design/#16 공식대회 화면 구성
  hustle_web/src/components/MatchButton/MatchButton.tsx
  hustle_web/src/components/MatchButton/MatchButtonProps.ts
  hustle_web/src/components/MatchButton/Styles.ts
  hustle_web/src/components/MatchList/index.ts
  hustle_web/src/components/MatchStatus/MatchStatus.tsx
  hustle_web/src/components/MatchStatus/MatchStatusProps.ts
  hustle_web/src/components/MatchStatus/Styles.ts
  hustle_web/src/stories/MatchButton/MatchButton.stories.tsx
  hustle_web/src/stories/MatchStatus/MatchStatus.stories.tsx
  hustle_web/src/styles/Color.ts
Labels: Feature, 데이브/김원준, 🎨Design

#64 Feat63: 랭킹 컴포넌트 제작(수정중)
  hustle_web/src/components/RankList/RankList.tsx
  hustle_web/src/components/RankList/RankListProps.ts
  hustle_web/src/components/RankList/Styles.ts
  hustle_web/src/stories/RankList/RankList.stories.tsx
Labels: Feature, 데이브/김원준, 🎨Design

#68 Design/#65 랭킹 상세 페이지 디자인
  hustle_web/src/Router.tsx
  hustle_web/src/components/CompetitionInfo/Content/Content.tsx
  hustle_web/src/components/CompetitionInfo/Content/ContentProps.ts
  hustle_web/src/components/CompetitionInfo/Content/Styles.ts
  hustle_web/src/components/CompetitionInfo/Title/Styles.ts
  hustle_web/src/components/CompetitionInfo/Title/Title.tsx
  hustle_web/src/components/CompetitionInfo/Title/TitleProps.ts
  hustle_web/src/components/MatchList/MatchList.tsx
  hustle_web/src/components/MatchList/MatchListProps.ts
  hustle_web/src/components/MatchList/Styles.ts
  hustle_web/src/components/MatchList/index.ts
  hustle_web/src/components/TeamInfo/Styles.ts
  hustle_web/src/components/TeamInfo/TeamInfo.tsx
  hustle_web/src/pages/Competition/Competition.tsx
  hustle_web/src/pages/Competition/CompetitionApply/CompetitionApply.tsx
  hustle_web/src/pages/Competition/CompetitionApply/Styles.ts
  hustle_web/src/pages/Competition/Styles.ts
  hustle_web/src/routes.ts
  hustle_web/src/stories/Content/Content.stories.tsx
  hustle_web/src/stories/MatchList/MatchList.stories.tsx
  hustle_web/src/stories/Title/Title.stories.tsx
Labels: Feature, Style, 데이브/김원준

#71 Fix: 교류전 페이지 스타일 및 기능 수정
  hustle_web/src/components/DropDown/DropDown.tsx
  hustle_web/src/components/DropDown/Styles.tsx
  hustle_web/src/components/FriendlyMatchPage/ApplyMatch/ApplyForm.tsx
  hustle_web/src/components/FriendlyMatchPage/ApplyMatch/ApplyMatch.tsx
  hustle_web/src/components/FriendlyMatchPage/ApplyMatch/Styles.tsx
  hustle_web/src/components/FriendlyMatchPage/FriendlyMatchList/FriendlyMatchList.tsx
  hustle_web/src/components/FriendlyMatchPage/FriendlyMatchList/MatchListProps.ts
  hustle_web/src/components/FriendlyMatchPage/FriendlyMatchList/Styles.ts
  hustle_web/src/components/FriendlyMatchPage/MainMatch/FriendlyLists/InvitationLists.tsx
  hustle_web/src/components/FriendlyMatchPage/MainMatch/FriendlyLists/MatchLists.tsx
  hustle_web/src/components/FriendlyMatchPage/MainMatch/MainMatch.tsx
  hustle_web/src/components/FriendlyMatchPage/MainMatch/MatchTitle/MatchTitle.tsx
  hustle_web/src/components/FriendlyMatchPage/MainMatch/MatchTitle/Styles.tsx
  hustle_web/src/components/FriendlyMatchPage/MainMatch/Styles.tsx
  hustle_web/src/components/FriendlyMatchPage/MatchMenu/MatchMenu.tsx
  hustle_web/src/components/FriendlyMatchPage/MatchMenu/Styles.tsx
  hustle_web/src/components/FriendlyMatchPage/OtherMatchList/ListProps.ts
  hustle_web/src/components/FriendlyMatchPage/OtherMatchList/OtherMatchList.tsx
  hustle_web/src/components/FriendlyMatchPage/OtherMatchList/Styles.ts
  hustle_web/src/components/FriendlyMatchPage/PageButton/PageButton.tsx
  hustle_web/src/components/FriendlyMatchPage/PageButton/Styles.ts
  hustle_web/src/components/FriendlyMatchPage/PostMatch/InvitationForm.tsx
  hustle_web/src/components/FriendlyMatchPage/PostMatch/MatchForm.tsx
  hustle_web/src/components/FriendlyMatchPage/PostMatch/PostMatch.tsx
  hustle_web/src/components/FriendlyMatchPage/PostMatch/Styles.tsx
  hustle_web/src/components/SportsMenu/SportsMenu.tsx
  hustle_web/src/pages/FriendlyMatch/FriendlyMatch.tsx
  hustle_web/src/pages/Home/Styles.tsx
  hustle_web/src/pages/Home/index.tsx
  hustle_web/src/recoil/friendlyMatchPage/selectors.tsx
  hustle_web/src/recoil/friendlyMatchPage/states.tsx
  hustle_web/src/recoil/friendlyMatchPage/types.tsx
  hustle_web/src/stories/MatchTitle/MatchTitle.stories.ts
Labels: Fix, Style, 베스/엄선아

#72 Fix: 교류전 상세페이지 화면 수정
  hustle_web/src/components/FriendlyMatchPage/ApplyMatch/ApplyMatch.tsx
  hustle_web/src/components/FriendlyMatchPage/MatchDetail/MatchDetail.tsx
  hustle_web/src/components/FriendlyMatchPage/MatchDetail/Styles.tsx
Labels: Style, 베스/엄선아, 🎨Design

#74 Feat/#70 회원가입 기능 구현
  hustle_web/src/components/Header/index.tsx
  hustle_web/src/components/SignIn/GenderButton.tsx
  hustle_web/src/components/SignIn/SignIn.tsx
  hustle_web/src/components/SignIn/Styles.ts
  hustle_web/src/constants/FormRequirements.ts
  hustle_web/src/constants/defaultFormOption.ts
  hustle_web/src/constants/interfaces.ts
Labels: Feature, 베니/김도희

#77 fix/#70 성별 기능 추가
  hustle_web/src/components/MainCompetition/ApplyForm/ApplyForm.tsx
  hustle_web/src/components/MainCompetition/ApplyForm/DummyCompetition.tsx
  hustle_web/src/components/MainCompetition/PostCompetition/PostCompetition.tsx
  hustle_web/src/components/SignIn/DummyUniversityData.tsx
  hustle_web/src/components/SignIn/GenderButton.tsx
  hustle_web/src/components/SignIn/SignIn.tsx
  hustle_web/src/components/SignIn/Styles.ts
  hustle_web/src/components/SignIn/UniversitySearch.tsx
  hustle_web/src/constants/defaultFormOption.ts
  hustle_web/src/constants/interfaces.ts
Labels: Fix, 베니/김도희

#79 Feat/#71 대회 신청하기 정렬 스타일 수정, sportsmenu 제거
  hustle_web/src/components/MainCompetition/ApplyForm/ApplyForm.tsx
  hustle_web/src/components/MainCompetition/ApplyForm/Styles.tsx
  hustle_web/src/pages/MainCompetition/ApplyCompetition.tsx
Labels: Feature, Fix, 베니/김도희

#86 Fix83: 개인 득점 현황 관련 상태값 수정
  hustle_web/src/components/CompetitionPage/CompetitionDetail/CompetitionDetail.tsx
  hustle_web/src/components/CompetitionPage/CompetitionDetail/Styles.ts
  hustle_web/src/pages/Competition/CompetitionDetailResult/CompetitionDetailResult.tsx
  hustle_web/src/recoil/CompetitionPage/states.tsx
  hustle_web/src/recoil/CompetitionPage/types.tsx
Labels: Fix

#95 Feat/#93 대회 보기 화면 연동
  hustle_web/src/components/MatchList/MatchList.tsx
  hustle_web/src/components/MatchStatus/MatchStatus.tsx
  hustle_web/src/components/MatchStatus/MatchStatusProps.ts
  hustle_web/src/recoil/MatchList.tsx
  hustle_web/src/stories/MatchStatus/MatchStatus.stories.tsx
Labels: Feature, Fix, 데이브/김원준

#101 Fix : 대회결과 리스트 출력 수정
  hustle_web/src/components/CompetitionPage/CompetitionButton/MainCompetitionButton.tsx
  hustle_web/src/components/CompetitionPage/CompetitionButton/PreCompetitionButton.tsx
  hustle_web/src/components/CompetitionPage/MainList/MainList.tsx
  hustle_web/src/components/CompetitionPage/PreList/PreList.tsx
  hustle_web/src/recoil/CompetitionPage/CompetitionButton.tsx
  hustle_web/src/recoil/CompetitionPage/selectors.tsx
Labels: Fix, 베스/엄선아

#105 Feat99: 대회 신청하기 화면 연동
  hustle_web/src/Router.tsx
  hustle_web/src/components/CompetitionInfo/Title/Styles.ts
  hustle_web/src/components/CompetitionInfo/Title/Title.tsx
  hustle_web/src/components/MatchList/MatchList.tsx
  hustle_web/src/pages/Competition/CompetitionApply/CompetitionApply.tsx
  hustle_web/src/pages/Competition/CompetitionApply/Styles.ts
  hustle_web/src/recoil/MatchList.tsx
  hustle_web/src/routes.ts
Labels: Feature, Fix

#111 Fix/#108 푸터 위치 조정
  hustle_web/src/components/Content/Styles.tsx
  hustle_web/src/components/MatchStatus/Styles.ts
  hustle_web/src/pages/Home/Styles.tsx
Labels: Fix, 데이브/김원준, 🎨Design

#115 Fix: 대회 신청 정보 화면 사진 출력 수정
  hustle_web/src/pages/Competition/CompetitionApply/CompetitionApply.tsx
  hustle_web/src/recoil/MatchList.tsx
Labels: Fix

#119 Fix/#98 회원가입 기능 구현
  hustle_web/src/components/SignIn/SignIn.tsx
  hustle_web/src/components/SignIn/UniversitySearch.tsx
  hustle_web/src/constants/interfaces.ts
Labels: Fix, 베니/김도희

#124 Feat/#118 디테일 수정
  hustle_web/src/components/MatchStatus/MatchStatus.tsx
  hustle_web/src/components/MatchStatus/Styles.ts
  hustle_web/src/pages/Competition/CompetitionApply/CompetitionApply.tsx
Labels: Fix, 데이브/김원준
