Repository HUSTLE-UMC/HUSTLE_web, pull requests merged in 2023-07, with the labels that each got.

#9 [Feat] - #4 대회 일정, 교류전 컴포넌트 작성
  .idea/workspace.xml
  hustle_web/package-lock.json
  hustle_web/package.json
  hustle_web/src/App.tsx
  hustle_web/src/assets/icons/play.svg
  hustle_web/src/assets/icons/playOrigin.svg
  hustle_web/src/assets/images/Test.png
  hustle_web/src/assets/svg/Test.svg
  hustle_web/src/components/Button/index.js
  hustle_web/src/components/Button/index.stories.js
  hustle_web/src/components/Competition/Competition.ts
  hustle_web/src/components/Competition/CompetitionList.tsx
  hustle_web/src/components/Competition/list1.tsx
  hustle_web/src/components/Competition/styles.ts
  hustle_web/src/components/FriendlyMatch/FriendlyMatch.ts
  hustle_web/src/components/FriendlyMatch/FriendlyMatchList.tsx
  hustle_web/src/components/FriendlyMatch/list2.tsx
  hustle_web/src/components/FriendlyMatch/styles.ts
Labels: Feature, 데이브/김원준

#19 [Fix] - icon type error 해결
  hustle_web/src/components/CompetitionList/CompetitionList.tsx
  hustle_web/src/components/SportsButton/ButtonProps.ts
  hustle_web/src/components/SportsButton/SportsButton.tsx
  hustle_web/src/components/SportsButton/styles.tsx
  hustle_web/src/stories/CompetitionList/CompetitionList.stories.tsx
  hustle_web/src/stories/Examples/Button.stories.ts
  hustle_web/src/stories/Examples/Button.tsx
  hustle_web/src/stories/Examples/Header.stories.ts
  hustle_web/src/stories/Examples/Header.tsx
  hustle_web/src/stories/Examples/Page.stories.ts
  hustle_web/src/stories/Examples/Page.tsx
  hustle_web/src/stories/Examples/button.css
  hustle_web/src/stories/Examples/header.css
  hustle_web/src/stories/Examples/page.css
  hustle_web/src/stories/Icons/svg/index.ts
  hustle_web/src/stories/SportsButton/SportsButton.stories.ts
  hustle_web/src/stories/assets/Arrow.svg
  hustle_web/src/stories/assets/Sports/BaseBall.svg
  hustle_web/src/stories/assets/Sports/BasketBall.svg
  hustle_web/src/stories/assets/Sports/Etc.svg
  hustle_web/src/stories/assets/Sports/FootBall.svg
  hustle_web/src/stories/assets/Sports/Soccer.svg
  hustle_web/src/stories/assets/Sports/TableTennis.svg
  hustle_web/src/stories/assets/Sports/Tennis.svg
  hustle_web/src/stories/assets/Sports/VolleyBall.svg
  hustle_web/src/stories/assets/SportsButton.tsx
Labels: Fix, 베스/엄선아

#20 Chore/#17 레이아웃, 및 기타 환경 설정
  hustle_web/src/constants/styles/GlobalStyle.tsx
  hustle_web/src/index.tsx
  hustle_web/src/layout/DefaultLayout.tsx
Labels: Documentation, 데이브/김원준

#6 [Feat] - #1 Header
  hustle_web/src/assets/icons/alarm-active_icon.svg
  hustle_web/src/assets/icons/alarm-none_icon.svg
  hustle_web/src/assets/icons/header_logo.svg
  hustle_web/src/assets/icons/profile_icon.svg
  hustle_web/src/components/Header/LoginBtn.tsx
  hustle_web/src/components/Header/images.d.ts
  hustle_web/src/components/Header/index.tsx
  hustle_web/src/components/Header/styles.tsx
  hustle_web/src/constants/styles/colors.ts
  hustle_web/src/constants/styles/fonts.ts
  hustle_web/src/pages/home/index.tsx
  hustle_web/src/stories/assets/hamburger_icon.svg
  hustle_web/src/stories/assets/header_logo.svg
  hustle_web/src/stories/assets/profile_icon.svg
Labels: Feature, 베니/김도희

#35 [Style] - #34 운동버튼 스타일수정
  hustle_web/src/components/SportsButton/ButtonProps.ts
  hustle_web/src/components/SportsButton/SportsButton.tsx
  hustle_web/src/components/SportsButton/Styles.tsx
  hustle_web/src/components/SportsMenu/SportsMenu.tsx
  hustle_web/src/components/SportsMenu/Styles.tsx
  hustle_web/src/recoil/SportsButton.tsx
  hustle_web/src/stories/SportsButton/SportsButton.stories.ts
Labels: Style

#36 Feat/#26 반응형 웹 및 폰트 스타일
  .idea/HUSTLE_web.iml
  .idea/jsLibraryMappings.xml
  hustle_web/package-lock.json
  hustle_web/package.json
  hustle_web/public/index.html
  hustle_web/src/constants/styles/GlobalStyle.tsx
  hustle_web/src/layout/DefaultLayout.tsx
  hustle_web/src/styles/Font.ts
Labels: Feature, Style, 데이브/김원준

#37 Refactor/#33 헤더 리팩토링
  hustle_web/src/assets/icons/HeaderLogo.svg
  hustle_web/src/assets/logos/HeaderLogo.tsx
  hustle_web/src/assets/svg/HeaderLogo.svg
  hustle_web/src/components/Content/Styles.tsx
  hustle_web/src/components/Header/LoginBtn.tsx
  hustle_web/src/components/Header/Styles.tsx
  hustle_web/src/components/Header/index.tsx
  hustle_web/src/layout/DefaultLayout.tsx
  hustle_web/src/styles/Color.ts
Labels: Fix, Refactor, 데이브/김원준

#39 Style: #38 교류전 컴포넌트 디자인 수정
  hustle_web/src/assets/images/TempLogo.png
  hustle_web/src/components/FriendlyMatchPage/FriendlyMatchList/FriendlyMatchList.tsx
  hustle_web/src/components/FriendlyMatchPage/FriendlyMatchList/MatchListProps.ts
  hustle_web/src/components/FriendlyMatchPage/FriendlyMatchList/Styles.ts
  hustle_web/src/components/FriendlyMatchPage/FriendlyMatchList/list2.tsx
  hustle_web/src/components/FriendlyMatchPage/MainMatch/MatchLists/InvitationLists.tsx
  hustle_web/src/components/FriendlyMatchPage/MainMatch/MatchLists/MatchLists.tsx
  hustle_web/src/recoil/friendlyMatchPage/selectors.tsx
  hustle_web/src/recoil/friendlyMatchPage/states.tsx
  hustle_web/src/recoil/friendlyMatchPage/types.tsx
  hustle_web/src/stories/FriendlyMatchPage/FriendlyMatchPage.stories.ts
  hustle_web/src/styles/Color.ts
Labels: Style, 베스/엄선아
